# Generated by Django 3.1.4 on 2021-03-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('HotelCode', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=11)),
                ('Cost', models.IntegerField(default=1000)),
                ('Rating', models.IntegerField(default=5)),
            ],
        ),
    ]
