# Generated by Django 3.1.4 on 2021-03-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='Sno',
            new_name='id',
        ),
    ]
