# Generated by Django 3.1.4 on 2021-03-26 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_auto_20210325_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Rating',
            field=models.FloatField(default=5),
        ),
    ]
